title: Miles Bakenhus
description: Welcome to my page!
baseurl: ""
url: "https://mbakenhus.github.io" 

theme: cvless

# site settings
taglong: "" #Jekyll theme for a beautiful online CV
tagshort: "" #Jekyll theme
cv: true

# author settings
author:
  name: Miles Bakenhus
  email: milesbakenhus@gmail.com
photo: assets/files/selfie.jpg
joblines:
  - Chicago, IL
address: 4180 N Marine Drive
phone: +1 512 771 7165

# profile links
profile:
  linkedin: https://www.linkedin.com/in/miles-bakenhus-58036676
  github: https://github.com/mbakenhus

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
